IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[USUARIO](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,	
		[CUI] [nvarchar](15) NOT NULL,		
		[Nombre] [nvarchar](75) NOT NULL,	
		[Apellido] [nvarchar](75) NOT NULL,	
		[Password] [nvarchar](500) NOT NULL			
	 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY],
	CONSTRAINT [UNIQUE_USUARIO_CUI] UNIQUE NONCLUSTERED 
	(
		[CUI] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]

	INSERT INTO [dbo].[USUARIO] ([CUI], [Nombre], [Apellido], [Password]) VALUES ('1590839151601', 'Gustavo', 'Delgado', '123');

	PRINT N'CREATE TABLE [dbo].[USUARIO]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[USUARIO];

	PRINT N'DROP TABLE [dbo].[USUARIO]'
END