IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[COBRO]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[COBRO](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,	
		[MontoReal] [decimal](20, 2) NOT NULL,	
		[Monto] [decimal](20, 2) NOT NULL,	
		[MontoRestante] [decimal](20, 2) NOT NULL,	
		[FacturaId] [decimal](18, 0) NOT NULL,			
		[UsuarioId] [decimal](18, 0) NOT NULL,		
	 CONSTRAINT [PK_COBRO] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [dbo].[COBRO]  WITH CHECK ADD  CONSTRAINT [FK_COBRO_FacturaId] FOREIGN KEY([FacturaId])
	REFERENCES [dbo].[FACTURA] ([Id])
	ALTER TABLE [dbo].[COBRO]  WITH CHECK ADD  CONSTRAINT [FK_COBRO_UsuarioId] FOREIGN KEY([UsuarioId])
	REFERENCES [dbo].[USUARIO] ([Id])
	
	PRINT N'CREATE TABLE [dbo].[COBRO]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[COBRO];

	PRINT N'DROP TABLE [dbo].[COBRO]'
END