IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_PROMOCION]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[TIPO_PROMOCION](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,	
		[Nombre] [nvarchar](40) NOT NULL	
	 CONSTRAINT [PK_TIPO_PROMOCION] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]
	
	INSERT INTO [TIPO_PROMOCION] (Nombre) VALUES ('Descuento de Producto');
	INSERT INTO [TIPO_PROMOCION] (Nombre) VALUES ('Producto Gratuito');
	INSERT INTO [TIPO_PROMOCION] (Nombre) VALUES ('Segundo Producto a Mitad de Precio');
	INSERT INTO [TIPO_PROMOCION] (Nombre) VALUES ('Compra por Mayor');
	INSERT INTO [TIPO_PROMOCION] (Nombre) VALUES ('Puntos por Producto');
	
	PRINT N'CREATE TABLE [dbo].[TIPO_PROMOCION]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[TIPO_PROMOCION];

	PRINT N'DROP TABLE [dbo].[TIPO_PROMOCION]'
END