IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FACTURA]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[FACTURA](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,	
		[ClienteId] [decimal](18, 0) NOT NULL,		
		[CUI_NIT] [nvarchar](15) NOT NULL,		
		[Direccion] [nvarchar](250) NULL,	
		[Fecha] [datetime] NOT NULL,
		[Total] [decimal](20, 2) NOT NULL,	
		[CajaId] [decimal](18, 0) NOT NULL,		
		[Pagado] [bit] NOT NULL,	
		[TipoPago] [nvarchar](25) NOT NULL,	
	 CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_FACTURA_ClienteId] FOREIGN KEY([ClienteId])
	REFERENCES [dbo].[CLIENTE] ([Id])
	ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_FACTURA_CajaId] FOREIGN KEY([CajaId])
	REFERENCES [dbo].[CAJA] ([Id])

	ALTER TABLE [dbo].[FACTURA] ADD CONSTRAINT [DF_FACTURA_Pagado]  DEFAULT ((0)) FOR [Pagado]
	ALTER TABLE [dbo].[FACTURA] ADD CONSTRAINT [DF_FACTURA_TipoPago]  DEFAULT (('FALTA COBRO')) FOR [TipoPago]
	ALTER TABLE [dbo].[FACTURA] ADD CONSTRAINT [CHECK_FACTURA_TipoPago] CHECK([TipoPago] IN('CONTADO', 'TARJETA', 'CREDITO', 'PUNTOS', 'FALTA COBRO'))

	PRINT N'CREATE TABLE [dbo].[FACTURA]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[FACTURA];

	PRINT N'DROP TABLE [dbo].[FACTURA]'
END